/// Creado desde: http://localhost:52773/csp/healthshare/sergio/cysnet.sergio.ws.MiServicio.cls?WSDL
Class cysnet.sergio.wc.MiServicio.s0.EnsMessagebody Extends (%SerialObject, %XML.Adaptor) [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 1;

Parameter NAMESPACE = "http://tempuri.org";

Parameter XMLNAME = "Ens_Messagebody";

Parameter XMLSEQUENCE = 1;

Parameter XMLTYPE = "Ens_Messagebody";

Storage Default
{
<StreamLocation>^cysnet.sergED2F.EnsMessagebodyS</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
