/// Creado desde: http://localhost:52773/csp/healthshare/sergio/cysnet.sergio.ws.MiServicio.cls?WSDL
Class cysnet.sergio.wc.MiServicio.s0.EnsResponse Extends cysnet.sergio.wc.MiServicio.s0.EnsMessagebody [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 1;

Parameter NAMESPACE = "http://tempuri.org";

Parameter XMLNAME = "Ens_Response";

Parameter XMLTYPE = "Ens_Response";

Storage Default
{
<Type>%Storage.Serial</Type>
}

}
