Class cysnet.sergio.wc.MiServicio.rsp.crearPersonaResponse Extends Ens.Response [ ProcedureBlock ]
{

Property crearPersonaResult As cysnet.sergio.wc.MiServicio.s0.CrearPersonaResponse1;

Storage Default
{
<Data name="crearPersonaResponseDefaultData">
<Subscript>"crearPersonaResponse"</Subscript>
<Value name="1">
<Value>crearPersonaResult</Value>
</Value>
</Data>
<DefaultData>crearPersonaResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
